SELECT
    C.HISTORY_ID,
    C.CAR_ID,
    DATE_FORMAT(C.START_DATE, "%Y-%m-%d") AS START_DATE,
    DATE_FORMAT(C.END_DATE, "%Y-%m-%d") AS END_DATE,
    CASE
        WHEN 29 <= DATEDIFF(C.END_DATE, C.START_DATE)  THEN '장기 대여'
        ELSE '단기 대여'
    END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
WHERE (YEAR(C.START_DATE) = 2022 AND MONTH(C.START_DATE) = 9)
ORDER BY HISTORY_ID DESC;