SELECT
    F.ORDER_ID,
    F.PRODUCT_ID,
    DATE_FORMAT(F.OUT_DATE, "%Y-%m-%d") AS OUT_DATE,
    CASE
        WHEN DATE_FORMAT(F.OUT_DATE, "%m-%d") <= '05-01' THEN '출고완료'
        WHEN F.OUT_DATE IS NULL THEN '출고미정'
        ELSE '출고대기'
    END AS '출고여부'
FROM FOOD_ORDER AS F
ORDER BY ORDER_ID;