SELECT
    CR.CAR_ID,
    CASE
        WHEN CR.CAR_ID IN (
            SELECT R.CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R
            WHERE DATE '2022-10-16' BETWEEN R.START_DATE AND R.END_DATE
        ) THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY CR
GROUP BY
    CR.CAR_ID
ORDER BY
    CR.CAR_ID DESC;