SELECT DISTINCT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN (
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR C
    WHERE C.CAR_TYPE = '세단'
) J
ON H.CAR_ID = J.CAR_ID
WHERE EXTRACT(MONTH FROM H.START_DATE) = 10
ORDER BY H.CAR_ID DESC;
