SELECT
    C.HISTORY_ID,
    C.CAR_ID,
    TO_CHAR(C.START_DATE, 'YYYY-MM-DD') AS START_DATE,
    TO_CHAR(C.END_DATE, 'YYYY-MM-DD') AS END_DATE,
    CASE
        WHEN 29 <= (C.END_DATE - C.START_DATE)  THEN '장기 대여'
        ELSE '단기 대여'
    END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
WHERE EXTRACT(YEAR FROM C.START_DATE) = 2022 AND EXTRACT(MONTH FROM C.START_DATE) = 9
ORDER BY HISTORY_ID DESC;