SELECT
    C.CAR_ID,
    ROUND(AVG(DATEDIFF(C.END_DATE, C.START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
GROUP BY C.CAR_ID
HAVING 7 <= AVERAGE_DURATION
ORDER BY AVERAGE_DURATION DESC, C.CAR_ID DESC;