SELECT
    C.CAR_ID,
    ROUND(AVG((C.END_DATE - C.START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
GROUP BY C.CAR_ID
HAVING AVG((C.END_DATE - C.START_DATE) + 1) >= 7
ORDER BY AVERAGE_DURATION DESC, C.CAR_ID DESC;