SELECT
    U.BOARD_ID,
    U.WRITER_ID,
    U.TITLE,
    U.PRICE,
    CASE
        WHEN U.STATUS = 'DONE' THEN '거래완료'
        WHEN U.STATUS = 'SALE' THEN '판매중'
        ELSE '예약중'
    END AS price_category
FROM USED_GOODS_BOARD U
WHERE TO_CHAR(U.CREATED_DATE, 'YYYY-MM-DD') = '2022-10-05'
ORDER BY U.BOARD_ID DESC;
